### ISSUE TITLE
Search Rework

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#556]
- [x] Cookbook integration
- [x] and / or search
- [x] api pagination
- [x] Food/Keyword quick select
- [x] show recently added recipes #489
- [x] show day meal plan recipes
- [x] show recently viewed
- [x] image aspect ratio and scaling
- [x] use different screen resolutions nicely #418
- [x] internal/external badge
- [x] rating
- [x] type delay/performance test of continuous refresh
- [x] search api documentation
- [x] fix meal plan because api change probably broke it
- [x] re add include duplicates to app importer
- [x] fix keywords link passing (importer etc) .. -> in general create a way to pass parameters via get into search fields
- [x] fix going back on mobile not reloading search 
- [x] endless scroll / continue bottom
- [x] last cooked
- [x] fix pagination on back navigation (either back to paginated results or load previous pages when navigating back
- [x] pagination preference (some people might prefer pagination)
- [x] random recipe with base filter #5
- [x] sorting (verify alphabetical order, make ranking new recipes high optional)
- [x] fix recently viewed order (broke with rank update) ------ Count still broken
- [x] prevent long description texts from making huge cards @Kaibu 
- [x] book/keyword limit in dropdowns
- [ ] special pages #556 not sure if part of search or extra page
- [ ] wide style (one card per row)
- [ ] write tests for search results

Further Ideas
- Image display #214

**Comment by smilerz** [comment]
I'm not sure if you've noticed it yet - but the context menu on the recipes isn't working right.  I messed with it, but when I got it working on the search page it broke on the recipe view page.

**Comment by vabene1111** [comment]
ah thanks for the update, i will look into this (hadn't tested it yet, it also might be some options working some not, will need to verify this) other than that, how do you like the basics of the rework ?

**Comment by smilerz** [comment]
I like it a lot! and already incorporated it into my build.  And there is a ton of potential to do a lot more with it.  Very impressive.

**Comment by vabene1111** [comment]
Awesome, glad you like it. If you have any ideas not yet listed above feel free to let me know :)

**Comment by DiversityBug** [comment]
Hi, a search by one or more ingredients would be handsome. A restriction to search a specific Cookbook would be nice too. A filter by prep time or nutrition value could be helpful as well.

**Comment by smilerz** [comment]
@DiversityBug those are in his update

**Comment by Forceu** [comment]
It would be great if tag names are included in the search. Eg if I have the tag `asian` and search for "asian", all recipes tagged with `asian` should show up as well.

**Comment by smilerz** [comment]
> It would be great if tag names are included in the search. Eg if I have the tag `asian` and search for "asian", all recipes tagged with `asian` should show up as well.

Good news - I'm working on an update that will allow you to customize this.

**Comment by vabene1111** [comment]
@smilerz just so you know, i converted back to a paginated style as that made it easier to persist the page between searches and on back navigation (othrewise all previous results would need to load on each back navigation). 

In the future i might be able to implement a poper lazy loading system for an unpaginated style

**Comment by quamok** [comment]
I'm not sure if it's the intended way it's supposed to work, but when clicking the dropdown menu for keywords, ingredients and books in the new search, it only displays a few entries.

For instance, only 10 keywords appears in the dropdown menu, but 62 are present in my settings.

It would be nice to be able to see all keywords, select the ones we want and then search within those.

Thanks!

**Comment by vabene1111** [comment]
the dropdown fields are searchable, there are always 10 shown at first (the first 10 added in your instance) and after typing some characters the other ones should appear. Can you confirm this is the case ?

**Comment by quamok** [comment]
yes I confirm this is the case, but when you have a lot of keywords and a bad memory like me, you can't remember all 62 keywords you've set for my recipes :). I think it would be nice to be able to select keywords without starting to type something first.

**Comment by vabene1111** [comment]
hmm that is a valid point. The cap of 10 results is for performance reasons as loading everything in large instances might be slow (i for example have over 700 ingredients). But i see what you mean, i just choose 10 arbitrarily, I think I can increase the limit for keywords and books to 100 and just leave the ingredients at 20 or so because those will most likely always be searched

**Comment by smilerz** [comment]
> hmm that is a valid point. The cap of 10 results is for performance reasons as loading everything in large instances might be slow (i for example have over 700 ingredients). But i see what you mean, i just choose 10 arbitrarily, I think I can increase the limit for keywords and books to 100 and just leave the ingredients at 20 or so because those will most likely always be searched

The new keyword/etc views will allow browsing recipes by keyword.  Having limited drop downs that are searchable is a very common design pattern.  At best I'd suggest making the number configurable and leaving the default at 10.
