### ISSUE TITLE
MealPlan Refactor

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#895]
- [ ] list of "i want to cook this in the near future" or maybe generally some kind of recommendation system 🤔 
- [ ] search
- [ ] add
- [ ] calendar export
- [ ] edit/detail modal
- [ ] plan type edit modal (also new fields like color, icon) decide if user or space scoped

old plan related issues
- [ ] nutrition (maybe as part of a big health feature set) #336
- [ ] type differentiation (probably fix with user/space unique constraint) #281
- [ ] remove via drag and drop (optional in my option depending on other features) #115

**Comment by Kaibu** [comment]
Recipe search in the plan could be improved and rank higher if planned often/recently, instead of recommended list

**Comment by phfeustel** [comment]
@vabene1111 is it possible now(v.1.0.2) or planned to have the meal plan shared with other users? I like to share the plan for one week with my family members who are logged in as users.

**Comment by Kaibu** [comment]
@phfeustel I added recipe sharing and it's on dev already (https://github.com/TandoorRecipes/recipes/issues/1024). It's been a few very stressful weeks and we have not yet come around to another relesae.

It will be in the next Release for sure tho.

**Comment by michaelszubartowicz** [comment]
Just curious, does your bonus feature include a rolling system where I could cycle through a list of recipes with a selected tag?
I have some knowledge regarding recommender systems. If you need help, hit me up ;)

**Comment by vabene1111** [comment]
yes something like this is planned, we will make sure to get in touch if we hit a roadblock :) thanks!

**Comment by balanceofcowards** [comment]
>  advanced but cool: automatic, tag/book/ingredient/whatever based meal planing

+1 for this. In my view, a randomized "fill the next x weeks with random recipes" would already be a great first step. Anything beyond that would be truly awesome!
