### ISSUE TITLE
Health Refactor

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#896]
Collecting some ideas for building healt/nutrition related features, feedback welcome (especially from people who understand more about this than me)

- [ ] Show Nutrition of day on meal plan (maybe per serving), also included in #895 
- [ ] customizable list of tracked nutritional values #436 
- [ ] maybe calculate recipe nutrition based on ingredients (in combination with #327 )
- [ ] option to show nutritional stats on search page
- [ ] statistics page to show nutritions consumed/cooked, maybe even a log without recipe to log nutritions eaten outside of cooked recipes (or allow to plan them in note type meal plan entries)
- [ ] search for recipes with certain nutritional values

**Comment by kappa-london** [comment]
Hey guys,

Nutrition and Ingredients Matching is an essential part of the app - Coming from a cook!

I am thinking if we can build an ingredients list with nutri facts like:
https://fdc.nal.usda.gov/fdc-app.html#/food-details/170416/nutrients

And for when people create the recipe they would just search ingredients. -> I am willing to help with any front-end needed :dagger: 
K

**Comment by vabene1111** [comment]
awesome, thanks for the feedback, i am really looking forward to take a crack at this sadly rather busy right now but i will get back to you if i have any questions or need assistance

**Comment by gemmans** [comment]
Would be nice to include the Nutri Score and/or Multiple Traffic Lights as these give a quick rough assessment of healthy/not sooo healthy meals.

**Comment by sebimarkgraf** [comment]
A potentially confusing concept currently is the nutritional information for the whole recipe.
Most people expect a per serving based nutritional values, which would therefore not scale with the recipe.

This is important as it could influence the implementation of #895 and #327 

We should either change to a per serving based system or try to communicate the per recipe based values.

**Comment by vabene1111** [comment]
Maybe just add a little toggle to the nutritional information field to switch between one serving/complete as some people/recipes dont use serverings as actual servings but for example "pieces of food" e.g. when making meat balls a recipe could yield 12 balls and that could be in the servings field. But for that we can pull the servings text so that works. 

How this is going to implemented in he meal plan is a good question, i was thinking about that to, maybe i will just display some serving information.

**Comment by vabene1111** [comment]
some information on nutrition/healths

overview of calories per age/sex https://www.dietaryguidelines.gov/sites/default/files/2020-12/Dietary_Guidelines_for_Americans_2020-2025.pdf#page=152&zoom=100,68,68 

various kinds of trackable values https://www.dietaryguidelines.gov/sites/default/files/2020-12/Dietary_Guidelines_for_Americans_2020-2025.pdf#page=146

**Comment by 0rn0lf** [comment]
Would it be possible to implement nutritional data for ingredients which will automatically sum up in the recipe if you add them? This would be a big enhancement for everyone whos doing a diet based on nutritional data. 
For example, our son has to do ketogenic diet therapy for epilepsy. This is havily based on the informations about total fat, total carbohydrates and protein. To calculate the the ketogenic value of the recipe you have to divide fat by (carbohydrates + protein). 
But the process is the same for many other diets and nutritional data for ingredients with automatic sum up could massively simplyfy the process for people.

**Comment by vabene1111** [comment]
ok so i take two things from that.

1. summing up: thats already planned, i was thinking about making it so that you can store values on foods, go to the recipe and press "sum" and it will pull from all ingredients of the recipe and sum up the values
2. it would be cool if there could be "calculated" values that pull from others and apply some kind of formula

**Comment by Jbonnett** [comment]
I was thinking it might be good to break this into 2 different chunks, a unit refactor that makes units meaningful to the system, normalizes them across recipes and adds conversions between them rather than the current simple labels for numerical amounts. 

Then in a separate PR add the actual nutrition information refactor on top of that. 

Would you be interested in a pr that adds that extra unit metadata?  I have some time this week and would be happy to tackle it.

**Comment by vabene1111** [comment]
that exactly is the reason why i have not implemented this yet, unit conversion is a pre-requisite to this issue it just does not make sense otherwise. 

I really want to implement unit conversion myself as i think its a fun feature but given all the "clean up" work i still have to do I think it will likely take some time until i get to it so feel free to give it a try. What I would prefer though is that you open an issue with a detailed description on how you want to handle this as this is something quite fundamental that I will need to maintain afterwards for the next few years thus it must be desigended and crafted very carefully. I dont needs lots of prosa, just the most important changes to the database structure and how you plan on implementing key aspects so we can discuss if things need improvement or could be done in different ways.

Just out of my head right now things that i have in mind for the implementation
- using pint as the base library for conversion
- allowing for space wide "custom conversions" (or maybe per unit)
- what about food specific conversions (1 can of tomates has 400g but 1 can of beans has 500g)
- prefered units per Food but also in general (if no food specific preference is available use convertable unit with highest precedence) 
- do preferences need to be on a user or space level
- for the frontend i would probably implement all logic in the unit serializer to just add either a field or a list of "alternative" units to each unit returned either directly or in a nested serialization

generally speaking tandoor has a huge problem with being to complex for the user so we need to be very careful on how much complexity we add here.

**Comment by Jbonnett** [comment]
Sorry for the delay, but the unit refactor proposal is in #1954 for everyones perusal

**Comment by MarcusWolschon** [comment]
Is importing of existing "nutrition" block in scraped recipes being worked on?
(There is existing, tested and worting code. )

**Comment by vabene1111** [comment]
due to very limited time resources this is currently not being worked on. Before importing ingredients i need to change the nutrition system to not only allow the 4 hardcoded values but to choose whatever you want, after that the importer can create needed categories automatically.

**Comment by jlugao** [comment]
Hey, just started using Tandoor, so I might be missing something:

One important thing would be being able to specify what is the size of the portion you are specifying the nutrition facts for.

For instance, I'm adding Cuban pork chops recipe and I can add 106.22 Kcal per 100g or 337.6 Kcal per serving. It would be cool if we could choose when adding and have the app convert whenever we need

**Comment by MarcusWolschon** [comment]
Tandoor goes a different way in that the nutrifional facts **currently** don't correspond to 1 portion but to 1 recipe.
(I always have to use a calculator when importing new recipes.)

**Comment by vabene1111** [comment]
having a proper per portion scaling is definitely planned

**Comment by FuzzyWereBeast** [comment]
Would it be possible for those that are doing weight watchers to have a spot where they can put the amount of points the recipe is per serving?

**Comment by vabene1111** [comment]
yes, from the next version on it will. You can store the points on each ingredient and the recipe will be calculated automatically.

Quick Questions: In Weight watchers are points given per Ingredient or per Recipe or is it at least possible to find out the values for individual ingredients?

**Comment by FuzzyWereBeast** [comment]
Points are given on a per ingredient basis.  however, some items are free.  This can throw things off.  To top it all off, they update things every few years.  From the people I know that use Weight Watchers, the best thing would be to have a space for them to manually enter a per serving point that can be kept.

**Comment by dsm1212** [comment]
I noticed all the zero Properties on all my recipes. It looks like it should be nutritional data.  Sorry, I tried, but I'm having trouble finding documentation. Should it be automatically finding data for this somehow and is failing or do I enter it? When I edit the recipe it is not there to edit.

**Comment by vabene1111** [comment]
You can edit properties both on recipes in the editor and you can put values on all foods which will automatically be calculated for the recipe

**Comment by dsm1212** [comment]
I realized you are still working on this so not submitting an issue, but the few things I tried to enter as a food just won't take. Here's a simple one. Baking powder at 1tsp (or 4.6g) has 1.3g of carbs. I tried to enter this multiple ways and none will work correctly. 4.6g/1.3g is an error saving. 1tsp/1.3g won't save correctly, it says success but ends up saving 1g/1.3g and with that impossible combo for 1tsp in recipe it show 0.05g of carbs which is odd. 46g/13g will save but the carb calculation for 1tsp in a recipe is 0. Probably I'm not doing the right thing with units.

**Comment by VACIndustries** [comment]
RE: Custom Food and Recipe Properties -- is the ability to add a formula based calculation on them?  Aka determine the weight watchers points (custom property) per ingredient?  I know you had mentioned it was coming soon(TM).

Also; to state the obvious thank you for all the work you put into this -- it's been on my list to try and finally got to it today.  Absolutely amazing the amount you can do with this tool and I've barely scratched the surface I'm sure.
